# Generated by Django 4.2.11 on 2025-08-15 01:17

from django.db import migrations

def populate_status(apps, schema_editor):
    entries = {
        "published": "A post available for all to view",
        "draft": "A post only visable to the author",
        "arcived": "An older post visible only to logged user"
    }
    Status = apps.get_model("posts", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):
    

    dependencies = [
        ('posts', '0002_status'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
